import './globals.css'
import { ReactNode } from 'react'

export const metadata = {
  title: 'Diniz Express',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="PT-br">
      <body className="flex flex-col min-h-screen">
        <header className="bg-zinc-800 py-5 px-4">
          <ul className="flex gap-4 text-white text-lg">
            <a href="/">
              <li className="hover:text-red-500">HOME</li>
            </a>
            <a href="/services">
              <li className="hover:text-red-500">SERVIÇOS</li>
            </a>
            <a href="/cover">
              <li className="hover:text-red-500">COBERTURA</li>
            </a>
            <a href="/contact">
              <li className="hover:text-red-500">CONTATOS</li>
            </a>
          </ul>
        </header>
        {children}
        <footer className="bg-black mt-auto py-4 px-4 text-center justify-center flex">
          <ul className="flex gap-2 text-white">
            <li>Rua Macurape,41 São Paulo - SP</li>
            <a href="tel:+551141076090">
              <li className="hover:text-red-500">(11) 4107-6090</li>
            </a>
            <a href="tel:+551182546503">
              <li className="hover:text-red-500">(11) 8254-6503</li>
            </a>
            <a href="mailto:dinizexpress@hotmail.com">
              <li className="hover:text-red-500">dinizexpress@hotmail.com</li>
            </a>
          </ul>
        </footer>
      </body>
    </html>
  )
}
